---
title: "Chronicle_FYSurvey"
author: "Shari Tian"
date: "12/12/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
library(readxl)
library(knitr)
library(RColorBrewer)
library(wesanderson)
```

## Data

```{r data}
Survey_Responses <- read_excel("~/Survey Responses.xlsx", 
    sheet = "Sheet1")
View(Survey_Responses)
```

## Basic Demographics EDA

#### Overall ED

```{r countED}
Survey_Responses %>%
  count(ED) %>%
  mutate(prop = n/sum(n)) %>%
  kable()
``` 

```{r EDbar}
ggplot(data = Survey_Responses, mapping = aes(x = "", fill = ED)) +
  geom_bar(position = "fill") +
  scale_fill_brewer(palette ="Paired") +
  theme_minimal()+
  labs(title = "Did you apply to Duke via the Early Decision Process?", x = "", y = "")
  
```

#### Gender

```{r}
gender <- table(Survey_Responses$ED, Survey_Responses$Gender)
gender %>%
  kable()
```

```{r}
ggplot(data = Survey_Responses, mapping = aes(x = ED, fill = Gender)) +
  geom_bar(position = "fill") + 
  scale_fill_brewer(palette ="RdYlBu") +
  theme_minimal() +
  labs(title = "Gender", x = "Did you apply to Duke via the Early Decision process?", y = "")
```

#### Sexual Orientation

```{r}
sexuality <- table(Survey_Responses$ED, Survey_Responses$SexualOrientation)
sexuality %>%
  kable()
```

```{r}
ggplot(data = Survey_Responses, mapping = aes(x = ED, fill = SexualOrientation)) +
  geom_bar(position = "fill") + 
  scale_fill_brewer(palette ="Set2") +
  theme_minimal() +
  labs(title = "Sexual Orientation", x = "Did you apply to Duke via the Early Decision process?", y = "", fill = "Sexual Orientation")
```

#### Race

```{r}
race <- table(Survey_Responses$ED, Survey_Responses$Race)
race %>%
  kable()
```

```{r}
Survey_Responses$Race <- factor(Survey_Responses$Race,levels = c("NA", "American Indian or Alaska Native", "Asian,Native Hawaiian or Pacific Islander", "Asian,Other", "Black or African American,Asian", "Black or African American,Other", "White,Black or African American,Asian", "Other", "White,American Indian or Alaska Native", "White,Other", "White,Asian", "White,Black or African American", "Black or African American", "Asian", "White"))
```

```{r}
ggplot(data = Survey_Responses, mapping = aes(x = Race, fill = ED)) +
  geom_bar(position = "dodge") + 
  scale_fill_brewer(palette ="Paired") +
  theme_minimal() +
  coord_flip() +
  labs(title = "Race/Ethnicity", x = "Race/Ethnicity", fill = "Did you apply ED?")
```

#### Trinity or Pratt

```{r}
trinityorpratt <- table(Survey_Responses$ED, Survey_Responses$TrinityOrPratt)
trinityorpratt %>%
  kable()
```

```{r}
ggplot(data = Survey_Responses, mapping = aes(x = ED, fill = TrinityOrPratt)) +
  geom_bar(position = "fill") + 
  scale_fill_brewer(palette ="Paired") +
  theme_minimal() +
  labs(title = "Trinity vs. Pratt", x = "Did you apply to Duke via the Early Decision process?", y = "", fill = "Are you enrolled in Trinity or the Pratt?")
```

#### Major

```{r}
Survey_Responses %>%
  filter(ED == "Yes") %>%
  count(Major) %>%
  mutate(prop = n/sum(n)) %>%
  arrange(desc(prop)) %>%
  kable()
```

```{r}
Survey_Responses %>%
  filter(ED == "No") %>%
  count(Major) %>%
  mutate(prop = n/sum(n)) %>%
  arrange(desc(prop)) %>%
  kable()
```

## EDA specific to Early vs. Regular Decision

#### Varsity athlete

```{r}
ggplot(data = Survey_Responses, mapping = aes(x = ED, fill = VarsityAthlete)) +
  geom_bar(position = "fill") + 
  scale_fill_brewer(palette ="Paired") +
  theme_minimal() +
  labs(title = "Varsity Athlete", x = "Did you apply to Duke via the Early Decision process?", y = "", fill = "Are you a recruited varsity athlete?")
```


#### International

```{r}
ggplot(data = Survey_Responses, mapping = aes(x = ED, fill = International)) +
  geom_bar(position = "fill") + 
  scale_fill_brewer(palette ="Paired") +
  theme_minimal() +
  labs(title = "International Student", x = "Did you apply to Duke via the Early Decision process?", y = "", fill = "Are you an international student?")
```

```{r}
#ggsave("international.png")
```


#### Home community

```{r}
ggplot(data = Survey_Responses, mapping = aes(x = ED, fill = Community)) +
  geom_bar(position = "fill") + 
  scale_fill_brewer(palette ="RdYlBu") +
  theme_minimal() +
  labs(title = "Home Community", x = "Did you apply to Duke via the Early Decision process?", y = "", fill = "What type of community are you from?")
```
```{r}
#ggsave("HomeCommunity.png")
```

#### Family annual income

```{r}
Survey_Responses$FamilyAnnualIncome <- factor(Survey_Responses$FamilyAnnualIncome,levels = c("NA", "Below $40,000", "$40,000-$80,000", "$80,000-$125,000", "$125,000-$250,000", "$250,000-$500,000", "Above $500,000"))
```

```{r}
ggplot(data = Survey_Responses, mapping = aes(x = FamilyAnnualIncome, fill = ED)) +
  geom_bar(position = "dodge") + 
  scale_fill_brewer(palette ="Paired") +
  theme_minimal() +
  coord_flip() +
  labs(title = "Estimated Family Annual Income", x = "Estimated Family Annual Income", fill = "Did you apply to Duke via ED?")
```
```{r}
#ggsave("FamilyIncome.png")
```


```{r}
ggplot(data = Survey_Responses, mapping = aes(x = ED, fill = FamilyAnnualIncome)) +
  geom_bar(position = "fill") + 
  scale_fill_brewer(palette ="Set2") +
  theme_minimal() +
  labs(title = "Estimated Family Annual Income", x = "Did you apply to Duke via the Early Decision process?", y = "", fill = "Estimated Family Annual Income")
```
```{r}
#ggsave("FamilyIncome2.png")
```

#### Financial aid

```{r}
ggplot(data = Survey_Responses, mapping = aes(x = ED, fill = FinAid)) +
  geom_bar(position = "fill") + 
  scale_fill_brewer(palette ="Paired") +
  theme_minimal() +
  labs(title = "Financial Aid", x = "Did you apply to Duke via the Early Decision process?", y = "", fill = "Do you receive financial aid from Duke?")
```
```{r}
#ggsave("FinAid.png")
```

#### Interest in greek life and slgs

```{r}
Survey_Responses$Greek <- factor(Survey_Responses$Greek,levels = c("Extremely interested", "Very interested", "Moderately interested", "Slightly interested", "Not interested at all"))
```

```{r}
Survey_Responses$SLG <- factor(Survey_Responses$SLG,levels = c("Extremely interested", "Very interested", "Moderately interested", "Slightly interested", "Not interested at all"))
```

```{r}
ggplot(data = Survey_Responses, mapping = aes(x = ED, fill = Greek)) +
  geom_bar(position = "fill") + 
  scale_fill_brewer(palette ="Set2") +
  theme_minimal() +
  labs(title = "Interest in Greek Life", x = "Did you apply to Duke via the Early Decision process?", y = "", fill = "How interested are you in Greek life at Duke?")
```
```{r}
#ggsave("Greek.png")
```


```{r}
ggplot(data = Survey_Responses, mapping = aes(x = ED, fill = SLG)) +
  geom_bar(position = "fill") + 
  scale_fill_brewer(palette ="Set2") +
  theme_minimal() +
  labs(title = "Interest in SLG Life", x = "Did you apply to Duke via the Early Decision process?", y = "", fill = "How interested are you in SLG life at Duke?")
```
```{r}
#ggsave("SLG.png")
```


#### Type of secondary school

```{r}
ggplot(data = Survey_Responses, mapping = aes(x = ED, fill = SecondarySchoolType)) +
  geom_bar(position = "fill") +
  scale_fill_brewer(palette ="Set2") +
  theme_minimal() +
  labs(title = "Type of Secondary School Attended", x = "Did you apply to Duke via the Early Decision process?", y = "", fill = "What type of secondary school did you attend?")
```
```{r}
#ggsave("SecondarySchool.png")
```


#### Number of colleges and universities applied to

```{r}
EDYes <- 
  Survey_Responses %>%
  filter(ED == "Yes")
```

```{r}
EDNo <- 
  Survey_Responses %>%
  filter(ED == "No")
```

```{r warning = FALSE}
ggplot(data = EDYes, mapping = aes(x = NumApps)) +
  geom_histogram(binwidth = 1, fill = "#6699ff", color = "black") + 
  theme_minimal() +
  labs(title = "Number of Colleges/Universities Applied to Among ED Students", x = "Number of Colleges/Universities Applied to")
```
```{r}
#ggsave("EDNumApplied.png")
```


```{r warning = FALSE}
ggplot(data = EDNo, mapping = aes(x = NumApps)) +
  geom_histogram(binwidth = 1, fill = "#6699ff", color = "black") + 
  theme_minimal() +
  labs(title = "Number of Colleges/Universities Applied to Among RD Students", x = "Number of Colleges/Universities Applied to")
```
```{r}
#ggsave("RDNumApplied.png")
```


#### Legacy

```{r}
ggplot(data = Survey_Responses, mapping = aes(x = ED, fill = Legacy)) +
  geom_bar(position = "fill") + 
  scale_fill_brewer(palette = "Paired") +
  theme_minimal() +
  labs(title = "Legacy", x = "Did you apply to Duke via the Early Decision process?", y = "", fill = "Did any of your parents or siblings attend Duke?")
```
```{r}
ggsave("Legacy.png")
```

